#!/bin/bash

if [ "$1" == "" ]
then
    echo "Usage: $0 <version string>"
fi

if [ ! -e geoirc-$1.zip ]
then
    echo "geoirc-$1.zip not found."
    exit 1
fi

rm -r GeoIRC
unzip geoirc-$1.zip
chmod +x GeoIRC/geoirc
rm GeoIRC/*.bat
rm geoirc-*.tar.gz
cat GeoIRC/CHANGELOG-$1.txt | sed -e 's/\x0D//g' > temp
mv -f temp GeoIRC/CHANGELOG-$1.txt
cat GeoIRC/LICENSE | sed -e 's/\x0D//g' > temp
mv -f temp GeoIRC/LICENSE
tar zcvf geoirc-$1.tar.gz GeoIRC

exit 0