/*
 * GeoIRC.java
 *
 * Created on June 21, 2003, 11:12 AM
 */

package geoirc;

import com.l2fprod.gui.plaf.skin.*;
import java.awt.*;
import java.awt.event.*;
import java.beans.*;
import java.util.LinkedList;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.*;
import javax.swing.text.*;
import org.jscroll.*;

/**
 *
 * @author  Pistos
 */
public class GeoIRC
    extends javax.swing.JFrame
    implements
        GeoIRCConstants,
        ActionListener,
        KeyListener,
        CommandExecutor
{
    public static final String [] CMDS =
    {
        "sendraw",
        "newwindow",
        "join",
        "me", // emote/action
        "listfonts",
        "newserver",
        "nick",
        "nextwindow",
        "previouswindow"
    };
    public static final int UNKNOWN_COMMAND = -1;
    public static final int CMD_ACTION = 3;
    public static final int CMD_JOIN = 2;
    public static final int CMD_LIST_FONTS = 4;
    public static final int CMD_NEW_SERVER = 5;
    public static final int CMD_NEW_TEXT_WINDOW = 1;
    public static final int CMD_NEXT_WINDOW = 7;
    public static final int CMD_NICK = 6;
    public static final int CMD_PREVIOUS_WINDOW = 8;
    public static final int CMD_SEND_RAW = 0;
    
    protected static final int MAX_HISTORY_SIZE = 30;
    protected static final int MOST_RECENT_ENTRY = 0;
    
    protected Vector servers; // of Server objects
    protected DisplayManager display_manager;
    protected LinkedList input_history;
    protected int input_history_pointer;
    protected boolean input_saved;
    
    // SETMGR
    protected String current_nick;
    
    /** Creates new form GeoIRC */
    public GeoIRC()
    {
        initComponents();

        input_field.addActionListener( this );
        input_field.addKeyListener( this );
        input_field.grabFocus();
        input_field.setFont( new Font( "Lucida Console",  Font.PLAIN, 14 ) );
        
        servers = new Vector();
        input_history = new LinkedList();
        input_history_pointer = MOST_RECENT_ENTRY;
        input_saved = false;
        
        display_manager = new DisplayManager( getContentPane(), menu_bar );
        
        current_nick = "Pistos|GeoIRC";
    }
            
    // Returns the Server created.
    protected Server addServer( String hostname, String port )
    {
        Server s = new Server( this, display_manager, hostname, port );
        servers.add( s );
        GITextWindow window = display_manager.addServerWindow( s );
        
        return s;
    }
    
    /* Returns the RemoteMachine associated with the currently active window.
     * Returns null if the currently active window is not associated with
     * any remote machine.
     **/
    /*
    protected RemoteMachine getCurrentRemoteMachine()
    {
        JInternalFrame active_frame = display_manager.getSelectedFrame();
        
        if( active_frame == null )
        {
            return null;
        }
        
        
        
        GITextWindow tw;
        try
        {
            tw = (GITextWindow) active_frame;
        }
        catch( ClassCastException e )
        {
            return null;
        }
        
        return tw.getAssociatedMachine();
    }
     */
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        input_field = new javax.swing.JTextField();
        menu_bar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getContentPane().add(input_field, java.awt.BorderLayout.SOUTH);

        file_menu.setText("File");
        menu_bar.add(file_menu);

        setJMenuBar(menu_bar);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    protected void addToInputHistory( String text )
    {
        input_history.addFirst( text );
        if( input_history.size() > MAX_HISTORY_SIZE )
        {
            input_history.removeLast();
        }
    }
    
    // When the user presses enter in the text field, this method is called.
    public void actionPerformed( ActionEvent event )
    {
        String text = input_field.getText();
        if( ( text == null ) || ( text.equals( "" ) ) )
        {
            return;
        }

        addToInputHistory( text );
        input_history_pointer = MOST_RECENT_ENTRY;
        input_saved = false;
        
        /* What we do with this input depends on its nature.
         * 
         * If the text starts with a backslash, we send it (without the
         * backslash) to the server as-is (raw).
         *
         * If the text starts with a slash, we must interpret it as a command
         * alias.
         *
         * All other text is sent to the current channel or chat, if any.
         */
        
        if( text.charAt( 0 ) == '\\' )
        {
            text = text.substring( 1 );
            execute( CMDS[ CMD_SEND_RAW ] + " " + text );
        }
        else if( text.charAt( 0 ) == '/' )
        {
            text = text.substring( 1 );
            execute( text );
        }
        else
        {
            String channel = display_manager.getSelectedChannel();
            if( channel != null )
            {
                execute(
                    CMDS[ CMD_SEND_RAW ]
                    + " privmsg "
                    + channel + " :"
                    + text
                );
            }
        }
        
        // Clear the input field.
        input_field.setText( "" );
        
    }    
    
    public void keyPressed(KeyEvent e) { }
    public void keyTyped( KeyEvent e ) { }
    public void keyReleased( KeyEvent e )
    {
        switch( e.getKeyCode() )
        {
            case KeyEvent.VK_UP:
                if( input_history_pointer < input_history.size() - 1 )
                {
                    String input_text = input_field.getText();
                    if( input_saved )
                    {
                        if( input_history_pointer == MOST_RECENT_ENTRY )
                        {
                            input_history.set( input_history_pointer, input_text );
                        }
                    }
                    else
                    {
                        addToInputHistory( input_text );
                        input_saved = true;
                    }
                    input_history_pointer++;
                    input_field.setText( (String) input_history.get( input_history_pointer ) );
                }
                break;
            case KeyEvent.VK_DOWN:
                if( input_history_pointer > MOST_RECENT_ENTRY )
                {
                    String input_text = input_field.getText();
                    input_history_pointer--;
                    input_field.setText( (String) input_history.get( input_history_pointer ) );
                }
                break;
        }
    }
    
    public int execute( String command )
    {
        int result = CommandExecutor.EXEC_GENERAL_FAILURE;
        int space_index = command.indexOf( " " );
        String command_name;
        String arg_string;
        if( space_index > -1 )
        {
            command_name = command.substring( 0, space_index ).toLowerCase();
            arg_string = command.substring( space_index + 1 );
        }
        else
        {
            command_name = command.toLowerCase();
            arg_string = null;
        }
        String [] args = Util.tokensToArray( arg_string );
        
        int command_id = UNKNOWN_COMMAND;
        for( int i = 0; i < CMDS.length; i++ )
        {
            if( command_name.equals( CMDS[ i ] ) )
            {
                command_id = i;
                break;
            }
        }
        
        switch( command_id )
        {
            case CMD_ACTION:
                String channel = display_manager.getSelectedChannel();
                if( channel != null )
                {
                    execute(
                        CMDS[ CMD_SEND_RAW ]
                        + " PRIVMSG "
                        + channel
                        + " :" + Character.toString( (char) 1 )
                        + "ACTION "
                        + arg_string
                        + Character.toString( (char) 1 )
                    );
                }
                break;
            case CMD_JOIN:
                if( args != null )
                {
                    Server s = (Server) display_manager.getSelectedRemoteMachine();
                    if( s != null )
                    {
                        GITextWindow window = display_manager.addChannelWindow( s, args[ 0 ] );
                        if( window != null )
                        {
                            execute( CMDS[ CMD_SEND_RAW ] + " " + command );
                            result = CommandExecutor.EXEC_SUCCESS;
                        }
                    }
                }
                break;
            case CMD_LIST_FONTS:
                GraphicsEnvironment genv = GraphicsEnvironment.getLocalGraphicsEnvironment();
                Font [] fonts = genv.getAllFonts();
                for( int i = 0; i < fonts.length; i++ )
                {
                    display_manager.printlnDebug( fonts[ i ].getName() + " -- " + fonts[ i ].getFontName() );
                }
                break;
            case CMD_NEW_SERVER:
                if( args != null )
                {
                    String host = args[ 0 ];
                    
                    int i_port = 6667;
                    String port = "6667";
                    if( args.length > 1 )
                    {
                        try
                        {
                            i_port = Integer.parseInt( args[ 1 ] );
                            port = args[ 1 ];
                        }
                        catch( NumberFormatException e )
                        {
                            // Ignore exception and use default port.
                        }
                    }
                    Server s = addServer( host, port );
                    // SETMGR
                    s.connect( current_nick );
                }
                else
                {
                    display_manager.printlnDebug( "/newserver <host> [port]" );
                }
                break;
                
            case CMD_NEW_TEXT_WINDOW:
                if( args != null )
                {
                    GITextWindow window = display_manager.addTextWindow( arg_string, arg_string );
                    if( window != null )
                    {
                        result = CommandExecutor.EXEC_SUCCESS;
                    }
                }

                break;
            case CMD_NEXT_WINDOW:
                display_manager.switchToNextWindow( NEXT_WINDOW );
                break;
            case CMD_NICK:
                if( args != null )
                {
                    current_nick = args[ 0 ];
                    
                    execute(
                        CMDS[ CMD_SEND_RAW ]
                        + " NICK "
                        + args[ 0 ]
                    );
                }
                else
                {
                    display_manager.printlnDebug( "Current nick: " + current_nick );
                    display_manager.printlnDebug( "/nick <new nickname>" );
                }
                break;
            case CMD_PREVIOUS_WINDOW:
                display_manager.switchToNextWindow( PREVIOUS_WINDOW );
                break;
            case CMD_SEND_RAW:
                {
                    Server s = (Server) display_manager.getSelectedRemoteMachine();
                    if( s != null )
                    {
                        s.send( arg_string );
                        if( args[ 0 ].toUpperCase().equals( IRCMSGS[ IRCMSG_PRIVMSG ] ) )
                        {
                            String text = Util.stringArrayToString( args, 2 ).substring( 1 );
                            if(
                                ( text.charAt( 0 ) == (char) 1 )
                                && ( text.substring( 1, 7 ).equals( "ACTION" ) )
                            )
                            {
                                text = current_nick + text.substring( 7, text.length() - 1 );
                            }
                            else
                            {
                                text = "<" + current_nick + "> " + text;
                            }
                            display_manager.println(
                                text,
                                s.toString() + " " + args[ 1 ]
                            );
                        }
                        result = CommandExecutor.EXEC_SUCCESS;
                    }
                }
                break;
            
            case UNKNOWN_COMMAND:
            default:
                display_manager.printlnDebug( "Invalid command name: " + command_name );
                result = CommandExecutor.EXEC_BAD_COMMAND;
                break;
        }

        input_field.grabFocus();

        return result;
    }

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /*
        System.setProperty( "proxyHost", "10.128.67.50" );
        System.setProperty( "proxyPort", "8000" );        
         */
        
        Skin skin = null;
        
        if( args.length > 0 )
        {
            try
            {
                skin = SkinLookAndFeel.loadSkin( args[ 0 ] );
                SkinLookAndFeel.setSkin( skin );
                UIManager.setLookAndFeel("com.l2fprod.gui.plaf.skin.SkinLookAndFeel");
                UIManager.setLookAndFeel( new SkinLookAndFeel() );
            }
            catch( Exception e )
            {
                e.printStackTrace();
            }
        }
        
        GeoIRC geoirc = new GeoIRC();
        geoirc.setExtendedState( MAXIMIZED_BOTH );

        geoirc.execute( "newserver irc.freenode.net 6667" );
        
        geoirc.show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu file_menu;
    private javax.swing.JTextField input_field;
    private javax.swing.JMenuBar menu_bar;
    // End of variables declaration//GEN-END:variables
    
}
